services:
  type_prediction_model:
    build:
      context: type_prediction
#      args:
#        - FOLDER=type_prediction_models
      dockerfile: ../Dockerfile
    ports:
      - "8000:80"
    # volumes:
    # - ./type_prediction_models:/type_prediction_models
  preprocessing_model:
    build:
      context: preprocessing
#      args:
#        - FOLDER=type_prediction_models
      dockerfile: ../Dockerfile
    ports:
      - "8001:80"
#    volumes:
#    - ./type_prediction_models:/type_prediction_models