FROM python:3.11.7-alpine

RUN python3 -m pip install --upgrade pip

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY . . 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]